### PR TITLE
Update Makefile and build files

### PR DESCRIPTION
**Pull request by tim-rix**
#### Helpful background context
Update Makefile and the dev-build and stage-build .yml files with new output
 from the appropriate workspace in Terraform Cloud

 Changes to be committed:
	modified:   .github/workflows/dev-build.yml
	modified:   .github/workflows/stage-build.yml
	modified:   Makefile

#### What are the relevant tickets?
[IN-514](https://mitlibraries.atlassian.net/browse/IN-514)
[IN-518](https://mitlibraries.atlassian.net/browse/IN-518)

#### Developer
- [X] All new ENV is documented in README
- [X] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer
- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Includes new or updated dependencies?
 NO

### CODE REVIEW

**Comment by cabutlermit** [comment]
@tim-rix this seems to be missing the `prod-promote.yml` workflow (found in the workloads-ecr-prod TfC workspace outputs).

**Comment by cabutlermit** [comment]
This all looks correct to me. @ehanson8 can you verify that the new `Makefile` in this branch works properly for you locally (the `make dist-dev`, `make publish-dev`, and `make update-lambda-dev` commands)? The GitHub Action workflows are all the same as what was pushed through [alma-webhook-lambdas](https://github.com/MITLibraries/alma-webhook-lambdas) today and verified.

**Comment by ehanson8** [comment]
All 3 worked just fine locally, everything updated in AWS as expected

**Review by cabutlermit — APPROVED** [review]
This all looks good.

**Pull request merged**
